{% set name = "upkie_description" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upkie_description-{{ version }}.tar.gz
  sha256: e57f5668452e8fb508235c152a5e0b8fdfe93f3c5735474c6d2ff37bd00054a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.7

test:
  imports:
    - upkie_description
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/upkie_description
  summary: URDF description for the Upkie wheeled biped.
  dev_url: https://github.com/upkie/upkie_description
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
